import type { Metadata } from "next";

import "@/styles/globals.css";

import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
