import type { Metadata } from "next";

import { Providers } from "@/providers/providers";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-center justify-center">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
